# yaml-language-server: $schema=./node_modules/envio/evm.schema.json
name: gorillionaire-indexer
networks:
  - id: 10143
    start_block: 0
    contracts:
      - name: Moyaki
        address:
          - 0xfe140e1dCe99Be9F4F15d657CD9b7BF622270C50
        handler: src/EventHandlers.ts
        events:
          - event: Approval(address indexed owner, address indexed spender, uint256 value)
          - event: Transfer(address indexed from, address indexed to, uint256 value)
